
		<main>
			<h2>Últimas 5 fotos</h2>
			<div class="fotosindex">
			<a href="detallefoto.html"><img src="../resources/foto1.jpg" alt="Foto"></a>
			<a href="detallefoto.html"><img src="../resources/foto2.jpg" alt="Foto"></a>
			<a href="detallefoto.html"><img src="../resources/foto3.jpg" alt="Foto"></a>
			<a href="detallefoto.html"><img src="../resources/foto4.jpg" alt="Foto"></a>
			<a href="detallefoto.html"><img src="../resources/foto5.jpg" alt="Foto"></a>
			</div>
		</main>
